export const AEROKLUBY = [
  "Aeroklub Bratislava o.z.",
  "Aeroklub Břeclav z.s.",
  "Aeroklub Brno‑Medlánky z.s.",
  "Aeroklub České Budějovice, z.s.",
  "Aeroklub Dvůr Králové n.L., z.s.",
  "Aeroklub Frýdlant nad Ostravicí",
  "Aeroklub Havlíčkův Brod z.s",
  "Aeroklub Hodkovice nad Mohelkou, z.s.",
  "Aeroklub Hořice v Podkrkonoší, z.s",
  "Aeroklub Hranice, z.s.",
  "Aeroklub Jaroměř z.s.",
  "Aeroklub Jičín z.s.",
  "Aeroklub Kolín z.s.",
  "Aeroklub Kralupy nad Vltavou, z.s.",
  "Aeroklub Krnov z.s.",
  "Aeroklub Martin",
  "Aeroklub MEMORIAL AIR SHOW Roudnice n.L. z.s.",
  "Aeroklub Mladá Boleslav z. s.",
  "Aeroklub Moravská Třebová, z.s.",
  "Aeroklub Nitra",
  "Aeroklub Nové Zámky, o.z.",
  "Aeroklub Praha Letňany, z.s.",
  "Aeroklub Prešov o.z.",
  "Aeroklub Přibyslav, z.s.",
  "Aeroklub Prievidza, o.z.",
  "Aeroklub Slaný, z.s.",
  "Aeroklub Šumperk z.s.",
  "Aeroklub Tábor, z. s.",
  "Aeroklub Vyškov, z. s.",
  "Aeroklub Žamberk z.s.",
  "Aeroklub Zbraslavice z.s.",
  "Slezský Aeroklub Zábřeh, z.s.",
  "Aeroklub Kroměříž z.s.",
  "Aeroklub České republiky, z.s.",
  "Glider Aerobatic Club (GAC) z.s."
];
