export const AEROKLUBY = [
  "Aeroklub Akademick\u00fd aeroklub \u010cVUT z.s.",
  "Aeroklub Bansk\u00e1 Bystrica o.z.",
  "Aeroklub Beroun z.s.",
  "Aeroklub Bratislava o.z.",
  "Aeroklub B\u0159eclav z.s.",
  "Aeroklub Brno-Medl\u00e1nky z.s.",
  "Aeroklub Brno-Slatina z.s.",
  "Aeroklub Broumov z.s.",
  "Aeroklub Byst\u0159ice z.s.",
  "Aeroklub \u010cesk\u00e1 L\u00edpa z.s.",
  "Aeroklub \u010cesk\u00e9 Bud\u011bjovice, z.s.",
  "Aeroklub \u010cesk\u00e9 republiky, z.s.",
  "Aeroklub Chomutov z.s.",
  "Aeroklub Chot\u011bbo\u0159 z.s.",
  "Aeroklub Dubnica nad V\u00e1hom o.z.",
  "Aeroklub Dv\u016fr Kr\u00e1lov\u00e9 n.L., z.s.",
  "Aeroklub Erpu\u017eice z.s.",
  "Aeroklub Fr\u00fddlant nad Ostravic\u00ed",
  "Aeroklub Havl\u00ed\u010dk\u016fv Brod z.s",
  "Aeroklub Hodkovice nad Mohelkou, z.s.",
  "Aeroklub Ho\u0159ice v Podkrkono\u0161\u00ed, z.s",
  "Aeroklub Ho\u0159ovice z.s.",
  "Aeroklub Hranice, z.s.",
  "Aeroklub Hronov z.s.",
  "Aeroklub Hol\u00ed\u010d o.z.",
  "Aeroklub Ji\u010d\u00edn z.s.",
  "Aeroklub Jihlava z.s.",
  "Aeroklub Jind\u0159ich\u016fv Hradec z.s.",
  "Aeroklub Jarom\u011b\u0159 z.s.",
  "Aeroklub Jesen\u00edk z.s.",
  "Aeroklub Karlovy Vary z.s.",
  "Aeroklub Karl\u0161tejn z.s.",
  "Aeroklub Kladno z.s.",
  "Aeroklub Kol\u00edn z.s.",
  "Aeroklub Ko\u0161ice o.z.",
  "Aeroklub Kralupy nad Vltavou, z.s.",
  "Aeroklub Krnov z.s.",
  "Aeroklub Krom\u011b\u0159\u00ed\u017e z.s.",
  "Aeroklub K\u0159i\u017eanov z.s.",
  "Aeroklub Kunovice z.s.",
  "Aeroklub Kyjov z.s.",
  "Aeroklub Liberec z.s.",
  "Aeroklub Lu\u010denec o.z.",
  "Aeroklub Martin",
  "Aeroklub MEMORIAL AIR SHOW Roudnice n.L. z.s.",
  "Aeroklub Mlad\u00e1 Boleslav z. s.",
  "Aeroklub Moravsk\u00e1 T\u0159ebov\u00e1, z.s.",
  "Aeroklub Most z.s.",
  "Aeroklub Nesva\u010dily z.s.",
  "Aeroklub Nitra",
  "Aeroklub Nov\u00e9 M\u011bsto nad Metuj\u00ed z.s.",
  "Aeroklub Nov\u00e9 Z\u00e1mky, o.z.",
  "Aeroklub O\u010dov\u00e1 o.z.",
  "Aeroklub Olomouc z.s.",
  "Aeroklub Panensk\u00fd T\u00fdnec z.s.",
  "Aeroklub Partiz\u00e1nske o.z.",
  "Aeroklub Plasy z.s.",
  "Aeroklub Plze\u0148-Bory z.s.",
  "Aeroklub Plze\u0148-Letkov z.s.",
  "Aeroklub Poli\u010dka z.s.",
  "Aeroklub Poprad o.z.",
  "Aeroklub Po\u0161umavsk\u00fd Klatovy z.s.",
  "Aeroklub Prachatice z.s.",
  "Aeroklub Praha Let\u0148any, z.s.",
  "Aeroklub Pre\u0161ov o.z.",
  "Aeroklub P\u0159ibyslav, z.s.",
  "Aeroklub P\u0159\u00edbram z.s.",
  "Aeroklub Prievidza, o.z.",
  "Aeroklub Rakovn\u00edk z.s.",
  "Aeroklub Ran\u00e1 u Loun z.s.",
  "Aeroklub Ru\u017eomberok o.z.",
  "Aeroklub Sabinov o.z.",
  "Aeroklub Senica o.z.",
  "Aeroklub Skute\u010d z.s.",
  "Aeroklub Slan\u00fd, z.s.",
  "Aeroklub Slavi\u010d\u00edn z.s.",
  "Aeroklub Sob\u011bslav z.s.",
  "Aeroklub Spi\u0161sk\u00e1 Nov\u00e1 Ves o.z.",
  "Aeroklub Sta\u0148kov z.s.",
  "Aeroklub Strakonice z.s.",
  "Aeroklub \u0160umperk z.s.",
  "Aeroklub T\u00e1bor, z. s.",
  "Aeroklub Tachov z.s.",
  "Aeroklub To\u010dn\u00e1 z.s.",
  "Aeroklub Tou\u017eim z.s.",
  "Aeroklub Tren\u010d\u00edn o.z.",
  "Aeroklub Trnava o.z.",
  "Aeroklub \u00dast\u00ed nad Labem z.s.",
  "Aeroklub \u00dast\u00ed nad Orlic\u00ed z.s.",
  "Aeroklub Vla\u0161im z.s.",
  "Aeroklub Vy\u0161kov, z. s.",
  "Aeroklub Vysok\u00e9 M\u00fdto z.s.",
  "Aeroklub V\u00fdchodo\u010desk\u00fd Pardubice z.s.",
  "Aeroklub \u017damberk z.s.",
  "Aeroklub \u017dilina o.z.",
  "Aeroklub Zbraslavice z.s.",
  "Slezsk\u00fd Aeroklub Z\u00e1b\u0159eh, z.s.",
  "Glider Aerobatic Club (GAC) z.s.",
  "Air Service PK Strunkovice nad Blan.",
  "Aviatic Sport Praha z.s.",
  "Base PK Praha z.s.",
  "\u010cesk\u00e1 para\u0161utistick\u00e1 asociace Prost\u011bjov z.s.",
  "Dad Air Letkov z.s.",
  "Han\u00e1ck\u00fd plachta\u0159sk\u00fd klub Olomouc z.s.",
  "Hurricane Flyers Club z.s.",
  "LAC \u010cR MT z.s.",
  "LC \u010cR z.s.",
  "Leteck\u00fd klub Chomutov z.s.",
  "Leteck\u00fd klub Karlovy Vary, z.s.",
  "Leteck\u00fd SK F AIR Byst\u0159ice u Bene\u0161ova z.s.",
  "Para Form Pardubice z.s.",
  "Para Sport klub Praha z.s.",
  "Parateam Praha z.s.",
  "PK Hranice z.s.",
  "PK Hole\u0161ov z.s.",
  "PK Jesen\u00edk z.s.",
  "PK Most z.s.",
  "PK Olymp Praha z.s.",
  "PK Ostrava z.s.",
  "PK \u0158\u00edp z.s.",
  "Plachta\u0159sk\u00fd spolek \u010cR z.s.",
  "SK Easy Sky z.s.",
  "SK Impact B\u0159eclav z.s.",
  "Technick\u00e9 sporty v\u00fdch. Morava Hole\u0161ov z.s.",
  "Tuebor Special Activity Plze\u0148 z.s.",
  "Turnovsk\u00fd aeroklub z.s.",
  "Krkono\u0161sk\u00fd aeroklub Vrchlab\u00ed, zapsan\u00fd spolek",
  "Podkrkono\u0161sk\u00fd aeroklub Star\u00e1 Paka z.s.",
  "Aeroklub Josefa Franti\u0161ka Prost\u011bjov z.s.",
  "Aeroklub Prost\u011bjov Stichovice z.s.",
];
